name: Build test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Build Test
        run: yarn build
